In [5]:
from utils import load_numpy

print(load_numpy(r"E:\Aidan\testing_extraction\np_coords\coord_1.npy"))



[[ 2451. -2313. -2106.]
 [ 2451. -2312. -2106.]
 [ 2451. -2311. -2107.]
 ...
 [ 2413. -3181. -2158.]
 [ 2413. -3181. -2158.]
 [ 2413. -3183. -2157.]]


In [3]:
print(load_numpy(r"E:\Aidan\plaques_extracted\np_indices\_index.npy", is_dict=True))

{'indices_0.txt': [' 0', ' 1143735'], 'indices_1.txt': [' 1143736', ' 2395657'], 'indices_10.txt': [' 11960084', ' 13153047'], 'indices_11.txt': [' 13153048', ' 14294581'], 'indices_100.txt': [' 111638964', ' 112852845'], 'indices_101.txt': [' 112852846', ' 114060769'], 'indices_102.txt': [' 114060770', ' 115286821'], 'indices_103.txt': [' 115286822', ' 116534567'], 'indices_104.txt': [' 116534568', ' 117627915'], 'indices_105.txt': [' 117627916', ' 118748901'], 'indices_106.txt': [' 118748902', ' 119956271'], 'indices_107.txt': [' 119956272', ' 121151017'], 'indices_108.txt': [' 121151018', ' 122418119'], 'indices_109.txt': [' 122418120', ' 123646697'], 'indices_110.txt': [' 123646698', ' 124850239'], 'indices_111.txt': [' 124850240', ' 125946081'], 'indices_112.txt': [' 125946082', ' 127079947'], 'indices_113.txt': [' 127079948', ' 128429041'], 'indices_114.txt': [' 128429042', ' 129891599'], 'indices_115.txt': [' 129891600', ' 131387089'], 'indices_116.txt': [' 131387090', ' 1329811

In [8]:
import nrrd

ModuleNotFoundError: No module named 'nrrd'